### ISSUE TITLE
Checar Nome das colunas no banco

### ISSUE THREAD

**Issue by BeaCristina** [jvvoliveira/OrdemServico#1]
Estamos usando uma padronização:

- Tudo maiúsculo
- A nomenclaturas são:  NOMEDATABELA_NOME_DA_COLUNA
- As chaves estrangeiras são: FK_NOMEDACHAVE

É preciso checar sem em todas as entidades isso está sendo seguido

**Comment by gida17** [comment]
Nomes checados - Em Pesso, ao invés do identificador ser COL_TIPO agora é PESS_TIPO
