### ISSUE TITLE
Implementar Gets and Sets

### ISSUE THREAD

**Issue by BeaCristina** [jvvoliveira/OrdemServico#2]
Ver qual Get e Set precisam de um tratamento especial.
Exemplos:

>  Um get and set de um atributo do tipo Lista<>

1. O set precisa ser um lista.add(item)
2. O get ser getLista(id_item_procurado), com o for percorrendo a lista e encontrado o item.
3. Precisa haver 2 Gets, um para recuperar a Lista inteira e outro um item da lista.

> Atributos transiente

1. Fazer implementação de get e set de valores transiente

**Comment by gida17** [comment]
métodos get and set feito
